### ISSUE TITLE
Please document which arduino version and RF24 library you are using.

### ISSUE THREAD

**Issue by bstromquist** [Pranavgulati/nrf_BLE_beacon#1]
I was not able to find an RF24 library that is compatible with your example. Have you made your own version?

I get these compile errors using arduino 1.6.5 (via visual micro) and github.com/maniacbug/RF24:

Compiling 'nrf_BLE_beacon' for 'Arduino Uno'
RF24BLE.cpp:In member function 'void RF24BLE::begin()
RF24BLE.cpp:82:9: error: 'class RF24' has no member named 'disableRX
:_radio.disableRX()
RF24BLE.cpp:83:9: error: 'class RF24' has no member named 'setAddressLength
:_radio.setAddressLength(4)
RF24BLE.cpp:97:35: error: no matching function for call to 'RF24::openWritingPipe(long unsigned int&, int)
:_radio.openWritingPipe(address, 4)
RF24BLE.cpp:candidate is
RF24BLE.h:In file included from
RF24BLE.cpp:from
RF24.h:openWritingPipe(uint64_t)
:void openWritingPipe(uint64_t address)
RF24.h:note    candidate expects 1 argument, 2 provided
Error compiling project sources

**Comment by Pranavgulati** [comment]
Oh,yes indeed i modified it, I'll move to the more recent rf24 library by TMRh20 ,it is maintained and has a few important bugs resolved.
I'll resolve this within 24 hrs

**Comment by Pranavgulati** [comment]
Updated the library to work with TMRh20/RF24 
tested using Arduino v1.6.5(windows) and Arduino v1.0.5 (ubuntu)

Please test, respond if it works and close the issue

**Comment by bstromquist** [comment]
Compiles cleanly now
