### ISSUE TITLE
i don't know why it is not working i'm using arduino 1.6.5

### ISSUE THREAD

**Issue by catchra** [Pranavgulati/nrf_BLE_beacon#2]
Using library SPI in folder: D:\arduino-1.6.5-r5\hardware\arduino\avr\libraries\SPI 

Using library RF24 in folder: D:\arduino-1.6.5-r5\libraries\RF24 

Using library nrf_BLE_beacon in folder: C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon (legacy)

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::RF24BLE(RF24&)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.cpp:6: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::RF24BLE(RF24&)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::BLEcrc(unsigned char const_, unsigned char, unsigned char_)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::checkCRC(unsigned char*, unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::bleWhiten(unsigned char*, unsigned char, unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::blePacketEncode(unsigned char*, unsigned char, unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::begin()'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::recvBegin(unsigned char, unsigned char, unsigned long)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::setPhone(unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::setMAC(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::setName(char*)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::setData(void const*, unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::sendADV(unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::printPacket()'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::getPacketLengthCurr()'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\nrf_BLE_beacon\RF24BLE.cpp.o: In function `RF24BLE::RF24BLE(RF24&)':

C:\Users\Haseo\Documents\Arduino\libraries\nrf_BLE_beacon/RF24BLE.h:23: multiple definition of `RF24BLE::recvPacket(unsigned char*, unsigned char, unsigned char)'

C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp\RF24BLE.cpp.o:C:\Users\Haseo\AppData\Local\Temp\build8137636527994024364.tmp/RF24BLE.h:23: first defined here
collect2.exe: error: ld returned 1 exit status

Error compiling.

**Comment by Pranavgulati** [comment]
hi would you please be able to share the code that you were working with, seems like the code had multiple definitions mayb due to improper inclusions

**Comment by catchra** [comment]
sry i should have said that as well im using the RF24_BLE_beacon example that comes with your code and no changes were made to it.

the arduino ide install is fresh with no extra libraries except for rf24 and your RF24_BLE_beacon.

**Comment by Pranavgulati** [comment]
i've understood what the issue is,
this repo was made on visual studio and not on the arduino IDE due to which there are duplicate files in the directory nrf_BLE_beacon/\* and nrf_BLE_beacon/RF24BLE/\* namely RF24BLE.cpp and RF24BLE.h hence the multiple definitions.

i'll reorganize the repo test and commit wiithin 24hrs, then you can delete all previous files and re-clone/download the repo

**Comment by catchra** [comment]
cool thx

**Comment by Pranavgulati** [comment]
you can now clone the latest build and test, i'm leaving this issue open so that you can close it if it works for you. Cheers!

**Comment by catchra** [comment]
great it compile with no problems thx
